### ISSUE TITLE
Support for JSON Feeds

### ISSUE THREAD

**Issue by samuelclay** [kurtmckee/feedparser#103]
https://jsonfeed.org/2017/05/17/announcing_json_feed

Once JSON Feed support hits feedparser, I can add it to NewsBlur, giving tens of thousands of readers access to JSON Feeds.

**Comment by bbolli** [comment]
Is anybody working on this already or should I give it a try in the next few weeks?

**Comment by bbolli** [comment]
Hey @samuelclay , have you tried my pull request #109? Does it work?

**Comment by samuelclay** [comment]
I havne't integrated this but I built it myself as an add-on for NewsBlur: https://github.com/samuelclay/NewsBlur/commit/c1834703d95345fffecb382cf75e47d90c46fed7

**Comment by MarcMV** [comment]
@kurtmckee any plans of adding JSON support? 👍

**Comment by MarcMV** [comment]
@kurtmckee do you have any plans to support it soon?

**Comment by klevstul** [comment]
@kurtmckee would be a great addition with json feed support.

**Comment by noMICROSOFTbuhtz** [comment]
JSON feeds are currently not a established standard nor ISO/RFC. Looks like an experiment.

Feedparser as enough problems on resources and shouldn't open new "construction areas".

**Comment by bbolli** [comment]
@noMICROSOFTbuhtz the JSONFeed addition is mostly orthogonal to the existing parser and doesn't touch much of the existing code, so I don't agree with your point.

**Comment by klevstul** [comment]
@noMICROSOFTbuhtz @bbolli @kurtmckee 

i've been using inoreader for years, and they started supporting json feed back [in 2017](https://blog.inoreader.com/2017/05/announcing-json-feed-support.html) when it was announced. it's not such a new construction area and it seems like a useful addition. as well, it looks like the code in the pull request is well separated from the existing code. so, if it's a goal to [support more](https://github.com/kurtmckee/feedparser/issues/103#issuecomment-385084261) than just xml feeds this seems like a step in the right direction.

**Comment by noMICROSOFTbuhtz** [comment]
btw: Can you name me some real world examples for JSON feeds.

While developing my own feedreader I have to think about supporting them, of course.

**Comment by klevstul** [comment]
@noMICROSOFTbuhtz 

one real-world example is parsing json feed from inoreader. 

example feed:
https://www.inoreader.com/stream/user/1005611799/tag/atestservice/view/json

**Comment by noMICROSOFTbuhtz** [comment]
Can you give me more real world examples? Googleing them is not easy. Can not found more.

Some aspects about the feed you gave as an example:

- The raw json data contains blanks (white space). This would blow up the transfer volume if the servers did not support data compression on a lower OSI layer.
- I can not see any eTag or modified date for the feed. How do I fetch feeds _not older then two days_ or  _not older from my last fetch_?

**Comment by bbolli** [comment]
> The raw json data contains blanks (white space). This would blow up the transfer volume if the servers did not support data compression on a lower OSI layer.

Most of the servers can compress the content if configured to do so. Just send the appropriate `Accept-Encoding` header.

> I can not see any eTag or modified date for the feed. How do I fetch feeds not older then two days or  not older from my last fetch?

The eTag header is present in the HTTP headers. Like compression, this is handled by the HTTP protocol, not inside content.

**Comment by bbolli** [comment]
@kurtmckee this branch is now ready for merging.

**Comment by Guts** [comment]
Hi @kurtmckee,

What did you finally decide about JSON Feed support? The situation described by @lemon24 (thanks for your comment, by the way, which saved me digging too deep into the code) seems to have remained the same since 2021, and it's not very clear.

Especially since the doc does mention the format as a supported one: https://feedparser.readthedocs.io/en/latest/introduction.html#introduction

Do you need some help or you don't want to support it at all?

**Comment by GreenLunar** [comment]
Please pardon me for commenting here.

It appears that feedparser is unable to parse JSON Feeds.

I am getting this result for any JSON Feed I attempt to parse:
```
{'bozo': 1, 'entries': [], 'feed': {'a': {'href': ''}, 'h4': {'id': ''}, 'img': {'src': ''}}, 'headers': {}, 'encoding': 'utf-8', 'version': '', 'bozo_exception': SAXParseException("Start tag expected, '<' not found"), 'namespaces': {}}
```

Please advise.

**Comment by bbolli** [comment]
@GreenLunar: There's no released version with JSON feed support yet. Did you use the development version?

Also, what's the URL of the feed that you tried to parse?

**Comment by sjehuda** [comment]
I'm willing to help testing JSON support of feedparser

I have added JSON Feed support to my XMPP News Bot, a couple of days ago.
https://gitgud.io/sjehuda/slixfeed/-/commit/0512e147381949d2d3239304b230c0d860a3d824

Not only the I have doubled my code lines (same function as XML with required changes for JSON), but I also wrote a JSON feed check in a dilapidated and frayed manner.

That would, of course, be changed with feedparser with support for JSON.

What's the status of the development? Can I be of assistance?

**Comment by GreenLunar** [comment]
> @GreenLunar: There's no released version with JSON feed support yet. Did you use the development version?
> 
> Also, what's the URL of the feed that you tried to parse?

It was JSON feed. I don't recall which that was. This result appears to
be consistent when attempting to parse JSON feeds using [python-feedparser 6.0.11-1](https://archlinux.org/packages/extra/any/python-feedparser/) which I suppose doesn't support it (yet); only development version as noted.
