### ISSUE TITLE
Parsed not exists rss, feedparser is stuck

### ISSUE THREAD

**Issue by f9n** [kurtmckee/feedparser#105]
Example rss: http://www.atilim.edu.tr/site/rss

```python3
>>> import feedparser
>>> url = 'http://www.atilim.edu.tr/site/rss'
>>> result = feedparser.parse(url)
                          ### Waiting
```

Solution: https://stackoverflow.com/questions/9772691/feedparser-with-timeout

**Comment by noMICROSOFTbuhtz** [comment]
This will become obsolete in the future because Kurt want to remove the HTTP part of the code. Feedparser should not be responsible for receiving data from any remote server.

So in future version you will `get()` (download) the data by yourself and after it hand it over to Feedparser for parsing.

**Comment by netllama** [comment]
Considering how its been nearly 4 years since since the last comment was made, are there any plans to change this behavior soon (where soon is in the next few months)?

**Comment by kurtmckee** [comment]
[This has been introduced recently](https://github.com/kurtmckee/feedparser/blob/d2d00088aa4c74351dc383e3af30750820494157/feedparser/http.py#L55-L59) and will go out in feedparser 7. There are several big-ticket items that need to be addressed before feedparser 7 is released, however.

In the meantime, it should still be possible for others to download the feed themselves using the `requests` module and pass the results in to feedparser for parsing.
