### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by AeolusDraco** [kurtmckee/feedparser#108]
There has not been much activity for this project for over a year.
I also see there quite a few issues related to general maintenance such updating the pypi package and supporting a new feed type.
I was wondering if this is still being maintained.

**Comment by tabbymarie** [comment]
Yeah, I was wondering the same. There's 13 pull requests that would really enhance feedparser.

**Comment by Miserlou** [comment]
Bump for this. Have patches to discuss and send, but not sure if it's worth opening them..

**Comment by anarcat** [comment]
@Miserlou i'd say it's better to send than to keep them in the dark. at least then they can be reused by a motivated fork, if needs be.

**Comment by buhtz** [comment]
I contacted @kurtmckee today by email and asked him to give an official statement about the current status and future plans here in the Issue.

**Comment by buhtz** [comment]
I would trully support a new maintainer **team**. But as one person I have not enough ressources in time and knowledge doing this alone.

**Comment by buhtz** [comment]
I also tried to contact @kurtmckee via an [Issue](https://github.com/kurtmckee/syncopath/issues/1) in another project where the last commit is only some days old.

Of course it is christmas and new year holiday. We have to wait.

To all others: I really would like to see this project coming back to life. I am not a well Python programmer or knowing a lot about web-communication (urllib, etc). So I can not do this by my own. But I really would like to join a new maintainer team and take some of the burden. ;)

**Comment by twm** [comment]
I, too, would be happy to join a maintainer team. As a first step I've gone through the recent issues and asked the folks who filed them to clarify where necessary.

**Comment by rachmadaniHaryono** [comment]
Hi @twm, will you merge the pr on this repo to your fork? It would be great if your fork have all the pr merged and hopefully some fix from the issue as well

**Comment by buhtz** [comment]
Just for your information. I was in contact with the maintainer per e-mail.
I don't want to give to much detailes here because he told me that he will post an official statement about the state of the project and future plans.
In summary he is alive and there is will and energy to keep the project alive and improve it.

**Comment by rachmadaniHaryono** [comment]
ok, i will wait

**Comment by kurtmckee** [comment]
Hey guys, I appreciate your patience, particularly in the face of my silence and apparent abandonment. Life and work colluded to drain me of both time and energy to do coding outside of work. I've been working on side projects for the past month or two to start picking up steam and get my head back in the game.

I apologize again for the extended delay. I'm going to leave this ticket open until I've done enough work to demonstrate that feedparser is being maintained again. It'll take time.

@Miserlou, send those patches and reports in! =)

**Comment by rachmadaniHaryono** [comment]
@kurtmckee would you mind add someone as collaborator, so they can merge the fix or answer the issue when you are not active?

**Comment by 6a7070** [comment]
This is exciting, I'm also interested in a new release of this project. Thank you.

**Comment by AeolusDraco** [comment]
So how is the progress so far?

**Comment by rachmadaniHaryono** [comment]
just give it some time, recent commit https://github.com/kurtmckee/feedparser/commit/5646f4ca2069ffea349618eef9566005afec665e is jan 29,

from related issue he also answer on feb 7 on # 122
