### ISSUE TITLE
Asyncio Support

### ISSUE THREAD

**Issue by lormayna** [kurtmckee/feedparser#116]
Good Morning, is there a plan to support asyncio instead that the "normal" urllib?
Regards

**Comment by twm** [comment]
See [my comment on #111](https://github.com/kurtmckee/feedparser/issues/111#issuecomment-357478078) for notes on how to use feedparser within an event-based I/O framework like asyncio or Twisted.

**Comment by kurtmckee** [comment]
@twm, excellent suggestion here!

@lormayna, I will eventually completely remove all HTTP code from feedparser; it doesn't belong in feedparser anymore. Likely this will be replaced with a dependency on the `requests` module, but as @twm said, for production code it'll be far better to write asynchronous code to fetch feeds and use feedparser exclusively for parsing them.

**Comment by noMICROSOFTbuhtz** [comment]
I would appreciate if we could keep the HTTP code **but** also offer an interface to use a third-party HTTP-lib (e.g. `aiohttp`).

I have no real idea about how much "HTTP code" is in Feedparser. But of course if it would save time, ressources to maintain and preventing bugs I also would agree with removing it.
