### ISSUE TITLE
status code different from urllib requests

### ISSUE THREAD

**Issue by buhtz** [kurtmckee/feedparser#118]
Maybe I missunderstand something or I find a bug?

Can you explain why the status codes for the same URL between `feedparser` adn `urllib` here are different?
```

>>> import feedparser
>>> import urllib
>>> a = 'http://www.aerzteblatt.de/rss/news.asp'
>>> af = feedparser.parse(a)
>>> au = urllib.request.urlopen(a)
>>> af.status
301
>>> au.status
200

```

btw: Both of them have content and are not empty.

**Comment by the01** [comment]
Your url redirects to the https:// version of the feed - hence the [301 status code](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.2). Feedparser just seems to be a bit more direct about it

**Comment by buhtz** [comment]
I am not sure if I get this.

301 means redirect. I understand this. urllib get a 301 the first step and then follow the redirect what results in a 200.
feedparser also follow the redirect but doesn't update the status code from 301 to 200?

How should I check if feedparser could retrieve the feeds correct? Currently I can not use the status code for this?

And how do I know the redirect address? The new address is not part of the header.

**Comment by buhtz** [comment]
I did some tests with my feeds.
`p = feedparser.parse(myurl)`

When I get the status code `301` or `302` I can see in most cases the new (redirected) URL with
`p.feed.title_detail.base`
I don't know if this is correct or standard conform.

But of course this doesn't work for all feeds. e. g. `http://fernsehkritik.tv/blog/feed/` give a `301` without any entries.

**Comment by buhtz** [comment]
Can be closed I think. ;)
