### ISSUE TITLE
Sometimes receive Index Out of Range

### ISSUE THREAD

**Issue by heyquentin** [kurtmckee/feedparser#124]
I'm trying to parse a Reddit RSS feed.  Sometimes, not all the time, I receive a List Index Out of Range error.  [Here's a screenshot.](https://imgur.com/a/xzZYm)  My python script is as follows:

`#! /usr/bin/python`
`import feedparser`
`d = feedparser.parse('http://www.reddit.com/r/funny/new/.rss')`

`for i in range(0,8):`
`print d['entries'][i]['title'].encode('utf-8')`
`print "-"`

Anyone have any ideas?

**Comment by mgobi** [comment]
give this one a try. its in python3

#! /usr/bin/python
import feedparser
d = feedparser.parse('http://www.reddit.com/r/funny/new/.rss')
items = d.entries
for i in items:
    print (i.title.encode('utf-8'))
    print ("-")

**Comment by kurtmckee** [comment]
@heyquentin, I recommend looping over the *entries* instead of attempting to loop over the entry *indeces*:

Bad:

```
for i in range(len(d.entries)):
    # do something with `d.entries[i]`
```

Good:

```
for entry in d.entries:
    # do something with `entry`
```

I'm closing because this doesn't look like a feedparser issue.
