### ISSUE TITLE
Can't parser such a url

### ISSUE THREAD

**Issue by RingWong** [kurtmckee/feedparser#125]
Environment:
Ubuntu 16.04
Anaconda 4.4.0
Python 3.6.1
feedparser 5.2.1

Description:
Hi~ I am a fresh man to feedparser, recently I came across a problem. When I used the following code to parse a url, I receive no feedback, but this url can be parsed in Inoreader. How can I do to get the correct feedback using feedparser? Thanks!

```
url = 'http://news.baidu.com/ns?word=%C7%F8%BF%E9%C1%B4&tn=newsrss&sr=0&cl=2&rn=20&ct=0'

feedparser.parse(url)
```

The feedback is as follow:
```
{'feed': {}, 'entries': [], 'bozo': 1, 'headers': {'Content-Type': 'application/octet-stream', 'Date': 'Tue, 20 Mar 2018 06:37:05 GMT', 'Server': 'Apache', 'Tracecode': '22250728970473615626032014', 'Content-Length': '11', 'Connection': 'close'}, 'href': 'http://news.baidu.com/ns?word=%C7%F8%BF%E9%C1%B4&tn=newsrss&sr=0&cl=2&rn=20&ct=0', 'status': 200, 'encoding': 'utf-8', 'bozo_exception': SAXParseException('syntax error',), 'version': '', 'namespaces': {}}
```

**Comment by pieqq** [comment]
Hello,

copypasting the URL you gave in a browser such as Firefox gives me the following error:

```
XML Parsing Error: no root element found
Location: http://news.baidu.com/ns?word=%C7%F8%BF%E9%C1%B4&tn=newsrss&sr=0&cl=2&rn=20&ct=0
Line Number 1, Column 1:
^
```

So I think there is a problem with the URL you are trying to parse.

**Comment by RingWong** [comment]
Hello，
The URL can be visited now, but the feedback is still null.
```
{'feed': {}, 'entries': [], 'bozo': 1, 'headers': {'Content-Type': 'application/octet-stream', 'Date': 'Tue, 20 Mar 2018 06:37:05 GMT', 'Server': 'Apache', 'Tracecode': '22250728970473615626032014', 'Content-Length': '11', 'Connection': 'close'}, 'href': 'http://news.baidu.com/ns?word=%C7%F8%BF%E9%C1%B4&tn=newsrss&sr=0&cl=2&rn=20&ct=0', 'status': 200, 'encoding': 'utf-8', 'bozo_exception': SAXParseException('syntax error',), 'version': '', 'namespaces': {}}
```

**Comment by pieqq** [comment]
@RingWong Hello,

as you can see in the response, the `bozo` bit is set to 1, which means the XML feed has a problem (see [the documentation for more info about that bozo thing](https://pythonhosted.org/feedparser/bozo.html)).

```
>>> b = feedparser.parse('http://news.baidu.com/ns?word=%C7%F8%BF%E9%C1%B4&tn=newsrss&sr=0&cl=2&rn=20&ct=0')
>>> b.bozo
1
>>> b.bozo_exception
SAXParseException('syntax error',)
>>> b.bozo_exception.getException()
ExpatError('syntax error: line 2, column 0',)
```

It looks like there is a syntax error, but I'm not sure how to fix that...

**Comment by RingWong** [comment]
I see, Thank you very much! @pieqq

**Comment by buhtz** [comment]
Close

**Comment by kurtmckee** [comment]
@pieqq, thanks for testing this! It looks like the feed can be parsed now, so perhaps the site was making changes to their template or was experiencing a temporary outage...
