### ISSUE TITLE
Enforcing PEP479 Cause RuntimeError:  generator raised StopIteration in _gen_georss_coords

### ISSUE THREAD

**Issue by rgammans** [kurtmckee/feedparser#130]

**Comment by rgammans** [comment]
The generator function _gen_georss_coords in namespaces/georss.py  doesn't capture the StopIteration form the local value list.
Since this is uncaught it bubbles out of _gen_georss_coords() which is a generator in it's own right, but under PEP479 this is not correct behaviour.

A simple try: block should fix this (see PR)

**Comment by buhtz** [comment]
I try to check if this is fixed in Debian 10 and 11 (#198).
I can I reproduce it? Did the error happen just while `import feedparser`. I can not remember.

**Comment by kurtmckee** [comment]
@buhtz This was related to a GeoRSS implementation issue, but it should have manifested at run time, not at import time.
