### ISSUE TITLE
RuntimeError:StopIteration @ line 3777 _parse_georss_point()

### ISSUE THREAD

**Issue by emican86** [kurtmckee/feedparser#147]
Python 3.7
Feedparser 5.2.1
Attempted to parse 'http://rss.indeed.com/rss?q=python&l=Baltimore%2C+MD'
Raised RuntimeError: StopIteration.
Workaround: modified the try except at line 3777 to include RuntimeError, return None, and move on.
    except (IndexError, ValueError, RuntimeError):
        return None

**Comment by icemac** [comment]
Maybe a duplicate of #131.

**Comment by emican86** [comment]
Probably.  I wanted to test/confirm but I hit a snag setting up an env with rgammans fork.
