### ISSUE TITLE
DDoS protection by Cloudflare

### ISSUE THREAD

**Issue by embryo10** [kurtmckee/feedparser#152]
When trying to get this feed http://rlsbb.com/category/movies/feed/ I get a 503 response.
The reason is that the owner of the feed have put it behind Cloudfare.
When I use the Opera's (12.x) RSS reader it works OK.
I think it is because it uses the cookie that the site gives me.
Is there any way that I could bypass this.
I tried to change the UserAgent but its the same.
Any help would be greatly appreciated...

**Comment by kurtmckee** [comment]
It may be that the cloudscraper package could help here.
