### ISSUE TITLE
socks5

### ISSUE THREAD

**Issue by flipchan** [kurtmckee/feedparser#153]
Hey, has anyone got feedparser to work with a socks5 proxy? im not getting it to work using the handlers function and the only way(very ugly) is to use the set socket proxy hack or set the enviroment variable http_proxy,

Can anyone share how to get socks5 proxy working?

**Comment by flipchan** [comment]
its working when u in BSD/linux set the enviroment variable http proxy and force all connections throw that

**Comment by flipchan** [comment]
or use requests and use feedparser to parse the response

**Comment by kurtmckee** [comment]
Excellent, I'm glad to hear it!

Happy new year!

Kurt
