### ISSUE TITLE
feedparser repository - no longer maintained?

### ISSUE THREAD

**Issue by klevstul** [kurtmckee/feedparser#155]
this repository, unfortunately, does look unmaintained. if needed, i believe it is, is there someone that is willing to do a fork, merge the open pull requests and take responsibility for the future? maybe a team of users, as discussed in #108?

references:  
#108 
https://github.com/kurtmckee/feedparser/pull/131#issuecomment-443467549

**Comment by luoliyan** [comment]
I rely on this library for several other projects. Over the next couple of weeks I'm going to get my head around the internals and start merging in the existing pull requests. I'll see what happens after that. It would just be a shame for a quality library like this to waste away.

**Comment by kurtmckee** [comment]
Joseph, I really appreciate your kind words! Thank you!

I'll start pulling in merge requests starting next week and will start documenting the release process so I can start putting out releases again.

Thank you again for your kind words!

**Comment by luoliyan** [comment]
Glad to see the project is still in good hands. Let me know if you need any help.

**Comment by kurtmckee** [comment]
I definitely will! Thanks!

**Comment by pvizeli** [comment]
Is a new pypi version on the roadmap for Python 3.7 support?

**Comment by kurtmckee** [comment]
Yes. My first guess is that it will be a beta so that people can test the changes and provide feedback, then upgrade to an RC, then a full release.

**Comment by joanne-carbon** [comment]
Just wondering if you have a rough estimate on when the beta, RC and full release might take?

**Comment by impredicative** [comment]
I don't think we'll be seeing much more of this project. Someone should fork it, take the contributions, and carry the torch.

**Comment by kurtmckee** [comment]
I'll get a beta out as soon as possible. =)
 
-----Original Message-----

**Comment by joanne-carbon** [comment]
Thanks, looking forward to it!

**Comment by rpitera** [comment]
Looking forward to an updated release as this is no longer working correctly on Python 3.7.  Thanks for keeping it going!

**Comment by klevstul** [comment]
@kurtmckee 
you have done a fantastic job developing and maintaining feedparser for such a long time, mr mckee. a big thank you. like many others, i'm dependent on feedparser for a project of mine. you have [stated](https://github.com/kurtmckee/feedparser/issues/108#issuecomment-361099859) that you no longer have time to maintain this repository. which is perfectly fine and natural as our lives move on.

there are unsolved issues from as far back as 2015 and [the 3.7 bug](https://github.com/kurtmckee/feedparser/pull/131#issuecomment-443467549) was fixed almost two years ago, still without being released. hence, i believe it would be great if you are willing to pass the development torch over to someone else. someone that can fork this repo, merge the prs, and follow up the wonderful product you have made.

i'm not the right person to take over this project. however, maybe there is someone out there, or in here (@luoliyan?), that are able to help if you ask. what do you say, mr mckee?

cheers,
frode.


## feedparser on python 3.7 hotfix

for those waiting for [the 3.7 fix](https://github.com/kurtmckee/feedparser/pull/131), i might have a solution for you. as i'm using feedparser with 3.7 i've made a hotfix. the hotfix version of feedparser that works with 3.7 is located at:
https://gitlab.com/klevstul/muninn/raw/master/additional_resources/feedparser_hotfix/feedparser.py

i've made a little bash script that downloads the hotfix and overwrites the installed feedparser.py. the paths, of course, needs to be adjusted. check it out at:
https://gitlab.com/klevstul/muninn/blob/master/additional_resources/helper_scripts/feedparser_hotfix.sh

**Comment by rpitera** [comment]
@klevstul - You are a **true hero**, my friend.  This solved an issue I was having with a Home Assistant component that relied on feedparser.py.   Thank you **_very_** much for providing an interim solution until another hero can take over for Mr. McKee.  Cheers!

**Comment by kurtmckee** [comment]
@klevstul, thanks for your kind words! I do actually have a strong desire to continue working on feedparser, but I definitely need help!

What I said back at the beginning of 2018 was true but wasn't the whole story: I experienced pretty severe burnout at the end of 2015. While I was able to recover and continue working, I realized in the last month that it is still affecting me at home, even three years later. So I'm working on that.

I've merged a couple of pull requests this morning, and I'll continue doing a little bit each day to move forward.

Thanks again for your kind words. It is impossible to overstate how beneficial they were to read!

**Comment by iantrich** [comment]
@kurtmckee I'm happy to help out as well.

Burnout is real, I think we can all appreciate that and regardless if you decide to continue on feedparser or not, I think we are all very grateful for your work and wish you the best.

**Comment by rpitera** [comment]
@kurtmckee - My thoughts mirror @iantrich's in that I am eternally grateful for your work as I am sure multitudes of users who may not know you are.   I can't imagine the stress of maintaining a library, but whatever decisions you make going forward please know that your impact is real as is the gratitude we share as users.

**Comment by klevstul** [comment]
@kurtmckee, you are welcome. very nice to see and hear that you want to continue with this great project. i as well can mirror @iantrich and @rpitera words. i am truly grateful for what you have created and shared with the world out of goodwill. so, a huge thank you, once again.

i've never maintained a repository myself but by observing feedparser i get some idea of the time and energy required for running such a project. if you get onboard some people that could help you that sounds like a good idea. burnout is serious and real for sure, so taking care of yourself should be the number one priority.

all the best, mr. mckee!

by the way, a side note: i'm starting an interesting looking coursera course this week [on well-being](https://www.coursera.org/learn/the-science-of-well-being). the course has gotten great reviews. several practices taught there will help to prevent stress. maybe it's worth looking into?

**Comment by rpitera** [comment]
While I am not a dev, if I can be of help in testing or documentation I'd be glad to pitch in.  @iantrich can vouch for me. : )

**Comment by iantrich** [comment]
Any progress on a new release? I would love to get my plugin for Home Assistant back up and running. Thanks!

**Comment by klevstul** [comment]
@kurtmckee 
any news regarding the next release?

**Comment by kurtmckee** [comment]
I actually spent several hours today working on a cleanup branch to update the codebase to use more common idioms and syntax (set literals, dictionary comprehensions, "x not in container"), to use PEP8 names and whitespace, and to remove some try-except clauses that guard against standard library differences from the pre-Python 2.4 era (like base64 and binascii).

I'll publish a beta 6.0.0 release in the next couple of weeks. Note that only Python 2.7 and 3.5+ will be supported starting with 6.0.0.

**Comment by klevstul** [comment]
@kurtmckee 
this is wonderful news. all the best with version 6. i'm looking forward to the release.

**Comment by MarcMV** [comment]
@kurtmckee  this is awesome, can't wait. Please please please consider JSON support :)

**Comment by rpitera** [comment]
@kurtmckee thanks for your dedication!

**Comment by kurtmckee** [comment]
@MarcMV, I want feedparser to fully support JSON feeds, but not for 6.0.0 -- this next release is about getting the project moving again.

**Comment by MarcMV** [comment]
@kurtmckee Thank you for sharing your work! Can't wait.

**Comment by noMICROSOFTbuhtz** [comment]
@MarcMV I am the developer of a [Feedreader](https://codeberg.org/buhtz/Feedybus) and never heard about "JSON feeds". Can you give me a hint please? ;)

**Comment by kurtmckee** [comment]
Hey everybody, I've pushed a beta 6.0.0b1 release to PyPI. I'm looking for feedback before the full release. Thanks!

**Comment by kurtmckee** [comment]
Beta 6.0.0b2 is released. Please let me know if you encounter any issues! I'm expecting to have 6.0.0 released soon if there aren't any show-stopper issues.

**Comment by kurtmckee** [comment]
Beta 6.0.0b3 is released with a minor fix to an issue that was reported. Please let me know if you encounter any issues!

**Comment by Safihre** [comment]
@kurtmckee When do you think 6.0.0 will be ready for it's final release? Are there some milestones that still need to be achieved?

**Comment by kurtmckee** [comment]
6.0.0 has been released today. Please file tickets if you encounter issues.

Note that this release has breaking changes. Be sure to test in your dev environments and pin your requirements file versions if you encounter issues.

Note also that it is no longer possible to update `pythonhosting` with new documentation, and someone has taken the `feedparser` project name on Read the Docs. I've emailed that person and am eagerly awaiting a response. At this time, however, there is no authoritative source for updated documentation.
