### ISSUE TITLE
Unbound prefix

### ISSUE THREAD

**Issue by TvoroG** [kurtmckee/feedparser#156]
Hi! Thanks for the lib!

Is it possible to configure feedparser to ignore unbound prefix exception and keep parsing?

**Comment by kurtmckee** [comment]
Hey Marsel! Can you provide an example feed that is demonstrating this behavior? A URL is probably sufficient. Thanks!

**Comment by noMICROSOFTbuhtz** [comment]
I can not reproduce your problem. The feed parses well.

```
>>> url = 'https://daily.afisha.ru/export/rss/yandex_zen/'
>>> import feedparser as fp
>>> a = fp.parse(url)
>>> a.bozo
0
```

Beside of this I wouldn't recommand to hide "unbound prefix" errors. I have some cases here where this parsing error (bozo_exception) happens when the server redirects a Feed-URL to a new URL that isn't a feed but a normal website.

**Comment by TvoroG** [comment]
Maybe the rss feed has been fixed already. Thanks anyway for your help!

**Comment by Dreyk007** [comment]
Same error for RSS Channel: http://electronicintifada.net/blog/all/feed
Line 8: "<itunes:author>The Electronic Intifada</itunes:author>"
'itunes' is unbound. So feedparser return 0 entries.

It's possible to ignore this error and continue parsing the feed?
FeedParser version = 5.2.1
