### ISSUE TITLE
Example URLs in doc not valid

### ISSUE THREAD

**Issue by buhtz** [kurtmckee/feedparser#166]
The documentation use some example feeds.
e.g. In
https://pythonhosted.org/feedparser/introduction.html
this is used
http://feedparser.org/docs/examples/atom10.xml

But the URL is not valid. The server answers with 403.

**Comment by kurtmckee** [comment]
Thanks for pointing this out! I'll get this fixed soon! =)

**Comment by kurtmckee** [comment]
This should be fixed now.
