### ISSUE TITLE
Unify the changelog

### ISSUE THREAD

**Issue by kurtmckee** [kurtmckee/feedparser#171]
The changelog history is scattered across legacy files in the documentation and the `NEWS` files.

It must be unified in a consistent and predictable format.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Is there a standard for the file format or internal formating of a changelog file?
Or do you have a template or another project where it looks nice?

**Comment by kurtmckee** [comment]
I'm reviewing how towncrier works as a systemic solution but haven't made a decision yet.

**Comment by kurtmckee** [comment]
I'm closing for now. I want to focus on getting feedparser 6.0.0 released and closing some existing tickets.

**Comment by impredicative** [comment]
@kurtmckee Status of changelog?
