### ISSUE TITLE
Can this module parse a json website?

### ISSUE THREAD

**Issue by leopheard** [kurtmckee/feedparser#174]
I've had success parsing a HTML website with BeautifulSoup, but BS can't handle JSON obviously. I can also print the JSON output, but can't work out how to get BS to handle it.

**Comment by noMICROSOFTbuhtz** [comment]
Can you give an example about input and expected output please.

**Comment by leopheard** [comment]
Thanks, here's some examples:
JSON input example: 
[https://pastebin.com/cDQi6yga](url)

HTML required output (not all of it, just the title, episode .mp3, image and description etc. sections):
[https://pastebin.com/PcJVv660](url)

**Comment by noMICROSOFTbuhtz** [comment]
Your links are wrong. Try and click on them.

The [first example](https://pastebin.com/cDQi6yga) is not well formated and human unreadable. Please use pretty printing or json's indent parameter.

The second example confuses me. This is HTML. Feedparser should generate HTML content for you? This is definitly out of scope of Feedparser.

It is still unclear for me what do you need from Feedparser.

**Comment by leopheard** [comment]
Sorry, yeah those links didn't work for some reason:
Sample input: https://thisiscriminal.com/wp-json/criminal/v1/episodes?posts=10000&page=1
Prettified here: https://pastebin.com/3btuRPE8

I'm basically trying to take component parts from that JSON file e.g. title, mp3 link, one of the images, etc. and then pass it to BeautifulSoup but in a tagged format it can read?

Output formart tagging needed: [http://feeds.thisiscriminal.com/CriminalShow](url)

**Comment by noMICROSOFTbuhtz** [comment]
Sorry, I do not get it.
I do not see how Feedparser can help you here.

The output of Feedparser is JSON like data (dictionaries). So why do you wan't to input JSON data into Feedparser if the output format will be the same?

Maybe it depends on my english why I do not get it here!? Sorry. ;)

**Comment by kurtmckee** [comment]
@leopheard there is an open merge request to add support for JSON feeds. However, feedparser does not currently support JSON feeds. You can perhaps use the `json` module in Python's standard library to parse the JSON content and then interact with it like it's a Python dictionary.
