### ISSUE TITLE
Get absolutly all entries of a feed/blog

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [kurtmckee/feedparser#175]
As an example
https://www.pflege-reise.de/feed/

This feeds offers 10 entries when `parse()` without ETag or modfied date. But the blog behind that feed contains more then 10 entries.

I tried the trick to set a `modfied` date in the past. But the feed offers only the 10 newest entries.

Is there a way or a trick to get all entries? Maybe a magic field in the HTTP request header?

Or does this responsibility belong to the feed generator (the blog software) only?

**Comment by kurtmckee** [comment]
Some software does support GET parameters to allow for this kind of thing, but it's not universal that I'm aware of. I see that this website claims to be running Wordpress 5.2.2, which supports adding `?paged=2` and `?paged=3`, etc, to the feed URL.

This is exclusively controlled by the feed generator, so in the future you'll need to find out what the feed generator is and then investigate what options it supports. :smiley:
