### ISSUE TITLE
Create empty 'entries' but no 'status'

### ISSUE THREAD

**Issue by buhtz** [kurtmckee/feedparser#179]
Example feed https://tobiw.de/tbdm/feed

When parsing this feed `bozo` is 1 because of an SSL error.
But `entries` is created but empty.
But `status` is not.

I understand the latter. But I would expect that `entries` does not exist, too in the case of an SSL problem.

**Comment by kurtmckee** [comment]
Thanks for the update, Christian! I'm going to close this.
