### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by webmedic** [kurtmckee/feedparser#18]
Trying to use this on python3 and I'm getting this?
feedparser.py", line 1353
    ur'''(([a-zA-Z0-9\_\-\.\+]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?))(\?subject=\S+)?''',
                                                                                                                                                   ^
SyntaxError: invalid syntax

the error is pointing to the last set of ''' before the comma.

I have played with this for a few hours, spliting up the line turing it into a string, etc, etc and no matter what it doesn't like that line.

Thanks

**Comment by kurtmckee** [comment]
Have you run the code through 2to3 yet? The 'u' in front of the quotes suggests that this hasn't been done yet.

    2to3 -w feedparser.py

**Comment by webmedic** [comment]
yes I did that and now it works.
Of course it would have helped if I would have done that before I spent a
few hours correcting other issues by hand.

Thanks


Brook Humphrey
Energy Management Technician Major
Lane Community College
(541) 600-6074
Email address: webmedic@gmail.com

**Comment by kurtmckee** [comment]
I understand the frustration! feedparser development in the near-term is actually going to include making the code run in both Python 2 and Python 3 without running 2to3, so I expect that in a future release this will no longer be an issue.
