### ISSUE TITLE
Tests fail when chardet is installed

### ISSUE THREAD

**Issue by ByteCommander** [kurtmckee/feedparser#184]
When I run the standard tox test suite on the current develop branch (`cbe18d0`) in a pristine environment, all tests pass. However, as soon as I have `chardet` installed in my environment, I get failures:

`tox` output with `chardet` (current version 3.0.4) installed: [link to private Gist](https://gist.github.com/ByteCommander/0583c54e816f98f869e164f25ed9f967)

`tox` output with `chardet` (current version 3.0.4) and `cchardet` (current version 2.1.4) installed: [link to private Gist](https://gist.github.com/ByteCommander/071ea13ebc2170e5570a5a663b2d5b1d)

Having `cchardet` only installed doesn't seem to break the tests, probably because of the skipping conditions of some cases like `tests/illformed/chardet/big5.xml`:

```
SkipUnless:   __import__('chardet')
```

The broken test files are namely these four below, removing or renaming them makes the remaining tests pass:

- tests/illformed/chardet/big5.xml
- tests/illformed/chardet/euckr.xml
- tests/illformed/chardet/gb2312.xml
- tests/illformed/chardet/windows1255.xml

An easy way to reproduce the results is to simply append `chardet` to the package requirements in `setup.py`, like so:

```py
    install_requires = [
        'sgmllib3k;python_version>="3.0"',
        'chardet',
    ],
```

I need this to work because I'm trying to modify my fork of `feedparser` to become asynchronous, requiring the `aiohttp` library which introduces `chardet` as an indirect dependency. Alternatively I'd have to delete the failing tests and lower my coverage, potentially introducing incompatibilities compared to the original, although I'd like to avoid that.

**Comment by kurtmckee** [comment]
@ByteCommander I'm reviewing this. By adding chardet and cchardet as optional tox dependencies I can recreate the behavior you're describing. Now I need to confirm whether Big5 (as an example) can be detected by chardet or if it needs to be removed. I'll close this ticket once I've got a fix for this.
