### ISSUE TITLE
Accessing protected feeds fails. Base64 mishandling in http.py

### ISSUE THREAD

**Issue by course-correction** [kurtmckee/feedparser#187]
There are some bugs introduced in b055c67cc11e9ca3ee171ffcaf0c718c73fa8855 that disable accessing authenticated feeds. The base64 functions often expect or return byte objects when we are expecting to deal with strings. I will send a pull request with a bugfix tomorrow when I find some spare time.

**Comment by fribeiro1** [comment]
Currently, HTTP basic authentication doesn't work at all in 6.0.0b3 on Python 3.6.8.

**Comment by kurtmckee** [comment]
I intend to strip out the HTTP client code in feedparser and replace it with requests. Please migrate to an alternate HTTP client library (such as requests).
