### ISSUE TITLE
urlopen error SSL/TLS

### ISSUE THREAD

**Issue by bendikro** [kurtmckee/feedparser#19]
Some users are reporting this error (bozo_exception) on some servers:

> urlopen error [Errno 1] _ssl.c:490: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

Presumably it's related to changes to handle the Poodle vulnerability, as described in https://github.com/calmh/unifi-api/issues/22

**Comment by kurtmckee** [comment]
I'm open to a patch for this. The unifi-api report has nothing actionable for feedparser but links to a Python bug that was closed four years ago.

Long term, feedparser is going to drop its HTTP code and rely on a third-party library.

**Comment by bendikro** [comment]
[launchpad.net (ubuntu/e/openssl/+bug/861137)](https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/861137) may contain some more relevant info, specifically comment 18:

> Marc Deslauriers (mdeslaur) wrote on 2013-07-09: 
> The issue is actually with certain SSLv3 servers that don't understand the TLSv1.1 handshake and are closing the connection. This unfortunately can't be fixed on the client without disabling TLSv1.1, or forcing an SSLv3 connection.

**Comment by kurtmckee** [comment]
Thanks @bendikro!

**Comment by bendikro** [comment]
It turns out to be a python bug which has been fixed in [2.7.9](https://www.python.org/downloads/release/python-279/) where they backported Python 3.4's ssl module.

I doubt it's worth it to try to figure out a fix.

**Comment by kurtmckee** [comment]
Fantastic. Thanks for chasing that down!
