### ISSUE TITLE
Support for youtube namespace

### ISSUE THREAD

**Issue by azmeuk** [kurtmckee/feedparser#193]
Youtube feeds (such as [this one](https://www.youtube.com/feeds/videos.xml?channel_id=UC7_gcs09iThXybpVgjHZ_7g)) use their own namespace `http://www.youtube.com/xml/schemas/2015`.
In the feed several `yt:` tags are used

```xml
  <yt:videoId>YmOVoIpaPrc</yt:videoId>
  <yt:channelId>UC7_gcs09iThXybpVgjHZ_7g</yt:channelId>
```

I would love feedparser to handle this tags!
What do you think?

**Comment by masklinn** [comment]
feedparser seems to "handle" it fine, at least in the sense that the information is exposed?
```python
>>> f = feedparser.parse('https://www.youtube.com/feeds/videos.xml?channel_id=UC7_gcs09iThXybpVgjHZ_7g')
>>> f.entries[0].yt_videoid
'AK44wAvv2E4'
>>> f.entries[0].yt_channelid
'UC7_gcs09iThXybpVgjHZ_7g'
```
I guess there could be some issues / annoyance if youtube uses its prefixes inconsistently, but unless some elements require special handling that seems to be about it?

**Comment by kurtmckee** [comment]
@masklinn Thanks for checking this.

Explicit YouTube support can be added in the future, but based on this it appears there's no need to keep this specific request open.

@azmeuk Sorry for the delay in responding. Please ping back if there is still a gap here.
