### ISSUE TITLE
Documentation link returns 504 error

### ISSUE THREAD

**Issue by Niagara1000** [kurtmckee/feedparser#196]
https://pythonhosted.org/feedparser/
It returns 504 Gateway Time-out error message
<img width="354" alt="504 error github" src="https://user-images.githubusercontent.com/46457863/70395247-abc5e380-19b1-11ea-92a0-cbb610aefbb9.png">

**Comment by anarcat** [comment]
this works now

**Comment by kurtmckee** [comment]
@Niagara1000, sorry for the inconvenience! I'll be sure to update the docs when 6.0.0 is officially released. (It will soon be in its second beta.)
