### ISSUE TITLE
FeedParserDict gone in 6.0?

### ISSUE THREAD

**Issue by anarcat** [kurtmckee/feedparser#197]
Hi,

I've been working on a [feed parser based on feedparser for a while now](https://gitlab.com/anarcat/feed2exec/), and I was deriving the (public) FeedParserDict class in my own `Feed` object. Now it seems this class is totally gone from the module:

```python
>>> import feedparser
>>> feedparser.
feedparser.CharacterEncodingOverride(    feedparser.UndeclaredNamespace(          feedparser.http                          feedparser.sgml
feedparser.CharacterEncodingUnknown(     feedparser.absolute_import               feedparser.mixin                         feedparser.unicode_literals
feedparser.NonXMLContentType(            feedparser.api                           feedparser.namespaces                    feedparser.urls
feedparser.RESOLVE_RELATIVE_URIS         feedparser.datetimes                     feedparser.parse(                        feedparser.util
feedparser.SANITIZE_HTML                 feedparser.encodings                     feedparser.parsers                       
feedparser.ThingsNobodyCaresAboutButMe(  feedparser.exceptions                    feedparser.registerDateHandler(          
feedparser.USER_AGENT                    feedparser.html                          feedparser.sanitizer                     
>>> feedparser.FeedParserDict
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'feedparser' has no attribute 'FeedParserDict'
>>> feedparser.__version__
'5.2.1'
```

the latter is lying: that's actually 6.0.0b1 installed through pip.

should i switch away from using that class? what's the replacement?

**Comment by kurtmckee** [comment]
Sorry about that. It's in the `util.py` file now.

I'm prepping a 6.0.0b2, and I'm fixing the version in `feedparser.__init__`.

**Comment by kurtmckee** [comment]
I'm closing, but re-open if that doesn't resolve the issue.

**Comment by anarcat** [comment]
i can't seem to reopen. but can't we please add a simple `from util import FeedParserDict` in the base module so that i don't have to add logic glue to my code to be compatible with the two versions?

it seems silly to drop backwards compatibility like this when a one-liner would fix this. :)

thanks1

**Comment by kurtmckee** [comment]
I will adjust this so you don't have a try/except to deal with, but I wasn't under the impression that FeedParserDict was something that was offered by feedparser as a part of its public API. It's just a return object.

**Comment by kurtmckee** [comment]
feedparser 6.0.0b3 should have this fix. Please let me know if you encounter anything else! :grinning:

**Comment by anarcat** [comment]
>  I wasn't under the impression that FeedParserDict was something that was offered by feedparser as a part of its public API. It's just a return object.

if it's importable and visible from the API consumer, then it's public. :)

i still have to test the latest beta, but I'll assume this works now... 37fb87a2c6857bd152e4ec771bf8f9b2fb8b8d0e looks exactly like what i had in mind...

thanks so much!

**Comment by kurtmckee** [comment]
No problem! Let me know if 6.0.0b3 needs any other touch-ups!
