### ISSUE TITLE
[FR] async http feed loading

### ISSUE THREAD

**Issue by JuniorJPDJ** [kurtmckee/feedparser#199]
It would allow to load much feeds simultaneously and not wait for every connection to finish before starting new one.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Download the feeds via asyncio separatly from feedparser.
After that you can give feedparser the downloaded data to parse.

I implemented something like this. A combination of async-programming and multi-processing (not "threading"). I can fully fetch 250 feeds in less then 10 seconds. It is awsome.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
@kurtmckee #Close.

@JuniorJPDJ Sorry for my short reply. It is christmas holiday. If you are really interested please contact me via an Issue here https://codeberg.org/buhtz/Feedybus . I will explain you details and would show you my code in that case.

**Comment by JuniorJPDJ** [comment]
I wanted to do it this way to be honest, but then realized that feedparser is already handling much http things inside like content types, status codes etc. I'd like my code to work reliable and I'm not sure what I need to handle.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
You can download a feed's xml-file which every method you want. e.g. aiohttp, wget, whatever
Then you can give this file to `feedparser.parse()`. Of course in that case feedparser does nothing about "handling of https things".

You have to do this yourself. It is some work. I was not familar with http codes etc, too. But I tried and it works now. e.g. you have to take care of redirects etc.

**Comment by JuniorJPDJ** [comment]
I'm familiar with this things, but feedparser gives all this errors in one standarized way and I think it should be done inside.

**Comment by kurtmckee** [comment]
feedparser's internal HTTP code will be completely removed in a future release and developers will need to do their own HTTP work.

**Comment by slidenerd** [comment]
@Codeberg-AsGithubAlternative-buhtz if you do this, the feedparser is not sanitizing the downloaded text. how did you work around that?

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> @Codeberg-AsGithubAlternative-buhtz if you do this, the feedparser is not sanitizing the downloaded text. how did you work around that?

I am not sure what "sanitizing" means in that context?

**Comment by slidenerd** [comment]
@Codeberg-AsGithubAlternative-buhtz  THIS is the issue https://stackoverflow.com/questions/63325193/feedparser-is-not-sanitizing-html-text-downloaded-via-asyncio-aiohttp

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Then pleas see my comments to that question and add more informations. It is unclear what you are asking on SO and unclear what do you need and what do you expect. Give us (here) an example what Sanitazing mean in the context of feedparser.
