### ISSUE TITLE
Use of deprecated function base64.decodestring

### ISSUE THREAD

**Issue by ProgVal** [kurtmckee/feedparser#201]
Hi,

[base64.decodestring](https://docs.python.org/3/library/base64.html#base64.decodestring) is deprecated since Python 3.1; and it was removed recently in nightly/3.9.

This causes the following crash when importing feedparser:

```
  File "./plugins/RSS/plugin.py", line 41, in <module>
    import feedparser
  File "/home/travis/virtualenv/python3.9-dev/lib/python3.9/site-packages/feedparser.py", line 93, in <module>
    _base64decode = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'
```

A possible fix would be:

```
try:
    _base64decode = base64.decodebytes
except AttributeError:
    _base64decode = base64.decodestring
```

Thanks!

**Comment by kurtmckee** [comment]
This is great info! I'll visit this issue when I start testing on Python 3.9.

**Comment by tirkarthi** [comment]
I have created https://github.com/kurtmckee/feedparser/pull/206 since this blocks fedora build https://bugzilla.redhat.com/show_bug.cgi?id=1807186

**Comment by Pyth3rEx** [comment]
Still getting this issue today running python 3.9. I installed using pip, can't seem to find a newer version, but the depreciation issue is still present for me.

**Comment by ProgVal** [comment]
@Pyth3rEx Check your feedparser version is 6.0.0 or newer

**Comment by Pyth3rEx** [comment]
I'm usin feedparser 6.0.8, but the library I use is somehow forcing my feddparser 5.x to run even though I removed it. No clue how to approach this issue

**Comment by kurtmckee** [comment]
@Pyth3rEx I've opened #284 to discuss this. Please continue the discussion there. Thanks!
