### ISSUE TITLE
Handling http 301 in result['status']

### ISSUE THREAD

**Issue by m1m** [kurtmckee/feedparser#21]
Hi,
Many sites uses 3rd party software to distribute content (feedsportal, feedburner, etc.). In such case we always get 301 or 302  from http://mysite.com/feed to http://feeds.feedburner.com/mysite. In the end we get 200 or 304.

However `parse()` always return status set to 301. I think we should return final response code.
Here's my patch:
replace lines 
> 1969	    if hasattr(f, 'status'):
> 1970	        result['status'] = f.status

with 

> result['status'] = getattr(f, 'code', 0)

Or maybe we can add this as new entry in result (along with status)

**Comment by kurtmckee** [comment]
[HTTP 301 is "moved permanently"](http://en.wikipedia.org/wiki/HTTP_301). The purpose for returning this is to allow developers to update the original feed URL's to their new locations. Also, I'm expecting to strip out all of feedparser's HTTP code and using a third-party module such as ``requests``.

**Comment by m1m** [comment]
What if someone switches from feedburner to feedsportal (in my example)? If we start using new location directly we will lose that change. But if we use orginal URL we will get 301 to new location.

Therefore I think that 301 should be transparent to user and we should return final status code (or both of them)

**Comment by kurtmckee** [comment]
That's one possible outcome. Another is that the website owner is signaling to permanently move the feed URL and eventually retires the domain altogether. Then everything is lost.

HTTP is far outside of feedparser's scope and I'm going to be removing all of that code before the next major release.
