### ISSUE TITLE
Issue with Python 3.6.10 for feedparser

### ISSUE THREAD

**Issue by meetsushantpatil** [kurtmckee/feedparser#210]
I see following error with Python 3.6:
 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/local/home/user/feedparser-5.2.1/feedparser/feedparser.py", line 318
    raise AttributeError, "object has no attribute '%s'" % key
                        ^
SyntaxError: invalid syntax
 
I changed the line to :
raise AttributeError("object has no attribute '%s'" % key)
 
This works fine, do you know what’s the issue here? Are there any compatibility issues with Python versions?

**Comment by kurtmckee** [comment]
A new version of feedparser will be released soon. The code that's triggering this error does not exist in the master branch anymore.
