### ISSUE TITLE
feedparser cache

### ISSUE THREAD

**Issue by Inig0Montoya** [kurtmckee/feedparser#214]
we originally had an rss feed providing 30 items in a list but wanted to limit it to 8 for the purposes of shoving the feed results into an html email, but now when pulling that rss feed it's still pulling all 30 results even though the feed is only advertising 8. I believe they are cached somewhere but I can't figure out how to clear a cache or delete a flat file that feedparser is using to make it pull the new results every time.

I tried setting the `extra_headers <example.http.headers.request>` parameter. Cache-control: max-age=60 in the feedparser.py file but it wouldn't work anywhere I put it. 

Ideally I'd like to pull fresh contents each time and not cache anything, if I can script a file to be deleted or overwritten between parsing rss feeds that would be great. Any help would be appreciated.

**Comment by Inig0Montoya** [comment]
![image](https://user-images.githubusercontent.com/53946577/85320549-daf0fd80-b488-11ea-91c6-4f56ba327ae4.png)

also tried it in the application making the request, but that's not working either.

**Comment by kurtmckee** [comment]
feedparser has no code to cache anything between runs. If you're getting 30 entries it's because the server is returning 30 entries with each request.
