### ISSUE TITLE
failed to parse some url

### ISSUE THREAD

**Issue by richshaw2015** [kurtmckee/feedparser#215]
for example:
`https://www.mihu.live/index.php/feed/`

got:
```python
{'feed': {},
 'entries': [],
 'bozo': 1,
 'headers': {'Server': 'nginx',
  'Date': 'Sun, 28 Jun 2020 03:05:07 GMT',
  'Content-Type': 'text/html',
  'Transfer-Encoding': 'chunked',
  'Connection': 'close',
  'Vary': 'Accept-Encoding',
  'Content-Encoding': 'gzip'},
 'href': 'https://www.mihu.live/index.php/feed/',
 'status': 403,
 'encoding': 'utf-8',
 'bozo_exception': xml.sax._exceptions.SAXParseException('syntax error'),
 'version': '',
 'namespaces': {}}
```

**Comment by kurtmckee** [comment]
It appears that feedparser's built-in HTTP client is not interacting with the mihu.live server in a nice way. The server is returning HTTP 403 and an HTML document, not an actual feed.

If you install the requests package and use that, mihu returns a valid feed. As I intend to scrap the custom HTTP client in feedparser and use an established package like requests, I am going to close this issue -- no time will be invested to fix feedparser's HTTP client code. Please try using this to make your code more robust:

```python
import requests
import feedparser

doc = requests.get('https://www.mihu.live/index.php/feed/')
result = feedparser.parse(doc.text)
print(result.entries[1].title)  # Currently outputs "Oracle Live SQL——SQL在线练习平台"
```
