### ISSUE TITLE
pip package keeps upgrading all the time

### ISSUE THREAD

**Issue by zouhair** [kurtmckee/feedparser#22]
$ pip install --upgrade feedparser
        Collecting feedparser
          Using cached feedparser-5.2.0.post1.tar.bz2
        Installing collected packages: feedparser
          Found existing installation: feedparser 5.2.0
            Uninstalling feedparser-5.2.0:
              Successfully uninstalled feedparser-5.2.0
          Running setup.py install for feedparser
        Successfully installed feedparser-5.2.0
        $ pip install --upgrade feedparser
        Collecting feedparser
          Using cached feedparser-5.2.0.post1.tar.bz2
        Installing collected packages: feedparser
          Found existing installation: feedparser 5.2.0
            Uninstalling feedparser-5.2.0:
              Successfully uninstalled feedparser-5.2.0
          Running setup.py install for feedparser
        Successfully installed feedparser-5.2.0
        $ pip install --upgrade feedparser --no-cache-dir
        Collecting feedparser
          Downloading feedparser-5.2.0.post1.tar.bz2 (192kB)
            100% |████████████████████████████████| 192kB 471kB/s
        Installing collected packages: feedparser
          Found existing installation: feedparser 5.2.0
            Uninstalling feedparser-5.2.0:
              Successfully uninstalled feedparser-5.2.0
          Running setup.py install for feedparser
        Successfully installed feedparser-5.2.0
        $ pip install --upgrade feedparser --no-cache-dir
        Collecting feedparser
          Downloading feedparser-5.2.0.post1.tar.bz2 (192kB)
            100% |████████████████████████████████| 192kB 2.5MB/s
        Installing collected packages: feedparser
          Found existing installation: feedparser 5.2.0
            Uninstalling feedparser-5.2.0:
              Successfully uninstalled feedparser-5.2.0
          Running setup.py install for feedparser
        Successfully installed feedparser-5.2.0
        $

It looks like the setup.py says it's version 5.2.0 but sdist says otherwise

I am sorry if it the wrong place for this kind of bugs,

cheers

**Comment by kurtmckee** [comment]
I accidentally uploaded a 5.2.0 release with a clerical error while trying to set up a new PC for development and PyPI forbade me from uploading identical filenames a few minutes later. The only solution I could find without skipping 5.2.0 entirely was adding that "post1" suffix...

I'll put together another release that synchronizes the versions with the filenames.

**Comment by zouhair** [comment]
Excellent,

I have to give credit to the guys at #pypa@FreeNode for helping me figure it out

**Comment by swistakm** [comment]
@kurtmckee, I think you should be able to remove this version using PyPI UI and upload again using right version label. I did it few times so it is definitely possible.

**Comment by nicksloan** [comment]
I am also struggling with this issue. In favor of a speedy resolution.

**Comment by zsoobhan** [comment]
Pinning the version as ```5.2.0.post1``` works pretty well for now. 

```console
$ pip install feedparser==5.2.0.post1
```

```console

Downloading/unpacking feedparser==5.2.0.post1
  Downloading feedparser-5.2.0.post1.tar.bz2 (192kB): 192kB downloaded
  Running setup.py (path:/home/zsoobhan/.virtualenvs/chameleon/build/feedparser/setup.py) egg_info for package feedparser
    
  Requested feedparser==5.2.0.post1, but installing version 5.2.0
Installing collected packages: feedparser
  Found existing installation: feedparser 5.2.0
    Uninstalling feedparser:
      Successfully uninstalled feedparser
  Running setup.py install for feedparser
    
Successfully installed feedparser
Cleaning up...


```

**Comment by dustinfarris** [comment]
any chance of a 5.2.1 release to fix this?

**Comment by jeffcjohnson** [comment]
I'm having trouble with this as well.  Any fix planned?

**Comment by davidjb** [comment]
+1, perhaps just a new release would handle it.

**Comment by swistakm** [comment]
:clap:
I already lost hope that this get eventually fixed :)

**Comment by davidjb** [comment]
Perfect, installs without a problem.  Cheers!
