### ISSUE TITLE
Options to extract more info like image thumbnail and the parsed main contents

### ISSUE THREAD

**Issue by AnandMoorthy** [kurtmckee/feedparser#220]
Hi all,

I am using this tool for quite some time, just wondering this tool providing all the necessary details except the main image or thumbnail of the feed. am I missing anything here? or the extraction of the image of a feed is not an easy job?

**Comment by samuelclay** [comment]
Here's how NewsBlur does it (using stories from feedparser):

https://github.com/samuelclay/NewsBlur/blob/master/apps/rss_feeds/models.py#L2735-L2802

Basically it involves BeautifulSoup to parse the feed and extract all `img` tags with `src` attributes, and then tosses the feedburner urls.

**Comment by AnandMoorthy** [comment]
Ah! okay, I can do this. but it would be great if it part of the library. will see if I can find time to write it for feedparser.

**Comment by kurtmckee** [comment]
Hi @AnandMoorthy, thanks for asking about this! Based on your response to @samuelclay's suggestion, it seems like you're asking about extracting images from the item content, not from the feed itself. If this is the case, at this time I think that this type of feature must exist outside of feedparser.

I'm closing this ticket based on my interpretation of your question and response to Samuel. If I'm not understanding correctly, please comment again and I'll revisit this. Thanks!
