### ISSUE TITLE
Git tags for 6.0.0b2 and 6.0.0b3 missing?

### ISSUE THREAD

**Issue by hartwork** [kurtmckee/feedparser#221]
Hi!

It seems like PyPI has [releases `6.0.0b2` and `6.0.0b3`](https://pypi.org/project/feedparser/#history) that have no Git tag in here. Are there plans to add Git tags? Do you need help determining the best SHA1 for the tags?

Thanks and best, Sebastian

**Comment by kurtmckee** [comment]
I may have forgotten to push the tags! That's supposed to be part of the release process. I'll get that fixed shortly.

Thanks for reporting this!

**Comment by kurtmckee** [comment]
Sorry for the confusion. I've pushed tags -- and the merges to master -- to the repo. Thanks for bringing this to my attention!
