### ISSUE TITLE
Why doesnt this function in your sanitizer.py file work?

### ISSUE THREAD

**Issue by slidenerd** [kurtmckee/feedparser#227]
[THIS](https://github.com/kurtmckee/feedparser/blob/develop/feedparser/sanitizer.py#L884) is the function I am referring to, my belief is that it is supposed to remove unsafe attributes and elements from raw text

`
import feedparser
text = "what an amazing hack <script>console.log('hacked ya')</script> eh"
print(feedparser._sanitizeHTML(text, 'utf-8', 'text/html'))
`
prints the same thing
`"what an amazing hack <script>console.log('hacked ya')</script> eh"`

Am I missing something with encoding or _type?

**Comment by kurtmckee** [comment]
This is working in the develop branch. I'm about to release feedparser 6.0.0 so you can expect this to be working soon in a current release.

**Comment by slidenerd** [comment]
thank you very much i see you have 3 betas of the develop branch out at the moment, if it isnt too much to ask, when do you think the non dev branch is coming out

**Comment by kurtmckee** [comment]
I released 6.0.0 yesterday. =)
