### ISSUE TITLE
Remove all Python 2 compatibility code

### ISSUE THREAD

**Issue by kurtmckee** [kurtmckee/feedparser#228]
Now that feedparser 6.0.0 strips all Python 2 compatibility, it's time to remove all of the Python 2 compatibility code.

**Comment by Safihre** [comment]
That's some nice cleanup 🔥

**Comment by nKsnC** [comment]
![image](https://user-images.githubusercontent.com/47666274/94989928-dc16e800-05aa-11eb-8e58-1ed815b2b683.png)

Hi,pypi show py2 and py3。It's confusing。

**Comment by kurtmckee** [comment]
Hmm, I must need to add or remove something to restrict the wheel's supported versions. Thanks for pointing this out!
