### ISSUE TITLE
python3 setup.py install error

### ISSUE THREAD

**Issue by faustus25** [kurtmckee/feedparser#237]
Python3 setup install fails:

```
/feedparser$ sudo python3 setup.py install
  File "setup.py", line 40
    name = f"{name}_{os.getenv('NAME_SUFFIX')}"
                                              ^
SyntaxError: invalid syntax

```

**Comment by kurtmckee** [comment]
What version of Python 3 are you using? Only Python 3.6 and higher are supported, so a syntax error on an f-string line makes me guess that this is an unsupported version.

**Comment by faustus25** [comment]
Default version was v3.5.2 so switched to 3.6 and now it works!

**Comment by kurtmckee** [comment]
Huzzah! =)
