### ISSUE TITLE
F-strings not supported on Python 3.5

### ISSUE THREAD

**Issue by DADi590** [kurtmckee/feedparser#238]
Hi. There seems to be an issue which is f-strings. They're not supported in Python 3.5 (the version I'm using), only in 3.6+. Could this be changed an older way, like string.format(), please?

The error:
```
  File "/usr/local/lib/python3.5/dist-packages/feedparser/http.py", line 156
    new_pieces[1] = f'{url_pieces.hostname}:{url_pieces.port}'
                                                             ^
SyntaxError: invalid syntax
```

Thank you.

**Comment by kurtmckee** [comment]
No. Python 3.5 is end-of-life and will not be supported in feedparser anymore. Please consider upgrading soon.

I will yank the feedparser 6.0.0 release, which was missing a line that prevents it from being installed on unsupported versions. This will return you to 5.2.1 next time you install. I apologize for the inconvenience.

**Comment by DADi590** [comment]
I can't really upgrade the Python version because I'm running OpenMediaVault on my Raspberry Pi and I read upgrading Python might give errors on parts of the system. So I chose to never upgrade Python. And I'm lucky because I decided to give myself a day or 2 to upgrade OpenMediaVault from version 3 to 4 or I'd still have Python 2.7 there... And I didn't know 3.5 was in end-of-life. I thought it was only Python 2.7. Cool to know, thanks.

Hopefully this will still all work with that version haha. Anyways, then I'll edit the file myself. In case you'd fix that I wouldn't edit it myself, but in that case I will, so I can keep the version installed. No problems though. If it's not supported anymore, what to do ¯\_(ツ)_/¯.

Thanks in any case and have a good day!

**Comment by Safihre** [comment]
You could also try to use `pip install -U feedparser<6.0.0` to get the older release. This one will work for you.

**Comment by DADi590** [comment]
Ah don't worry. For now it was that error up there on that specific file. Only 2 lines. Was easy to fix. Though if I ever need more from the module and more files have errors I may downgrade using what you said up there, yes. But for now it seems it's working perfectly already after fixing the 2 lines on the file up there. Thanks though!
