### ISSUE TITLE
AttributeError: module 'feedparser' has no attribute '_parse_date'

### ISSUE THREAD

**Issue by acffordyce973** [kurtmckee/feedparser#240]
Version 6 of the package seems to remove/change the useful "_parse_date" function and the documentation has not been updated. Is there a new way to access this function or has it been removed?

**Comment by kurtmckee** [comment]
It's been moved to `feedparser.datetimes._parse_date()`, but it's not part of the public API.

What is your use case for accessing `_parse_date()`?
