### ISSUE TITLE
Feedparser output isn't in the correct JSON Format. Unable to deserialize into objects

### ISSUE THREAD

**Issue by henkdvries** [kurtmckee/feedparser#246]
Feedparsers generates a JSON like formatting, but the problem is that it uses single quotes (') instead of double (") which is needed for JSON standard. For this reason I can't directly deseriale the output of feedparser. 

I'm using an atom 1.0 feed, not sure if this is the case with other feeds.

![image](https://user-images.githubusercontent.com/45108194/95723329-531c4280-0c75-11eb-9015-ffaf0d06dca9.png)

**Comment by kurtmckee** [comment]
feedparser doesn't produce JSON.

It sound like you're printing the dictionary that feedparser returns and assuming that this is JSON output, or writing a representation of the result to a file. In this case, Python uses single quotes in the string representation of the dictionary.

You must import Python's `json` module (which is built into the standard library) construct a dictionary with the structure you want, then call `json.dumps(your_dictionary_here)`, which will generate a JSON-formatted string that you can either print or write to a file.

**Comment by henkdvries** [comment]
MB, I realised this now.

Op ma 12 okt. 2020 om 14:47 schreef Kurt McKee <notifications@github.com>:

**Comment by kurtmckee** [comment]
No problem, hope that gets you on track for the software you're creating!

**Comment by henkdvries** [comment]
I must say I'm very glad I stumbled upon your library because all other
libraries and software were pretty outdated.

Thanks for the quick reply and keep up the good work!

Op ma 12 okt. 2020 om 22:13 schreef Kurt McKee <notifications@github.com>:
