### ISSUE TITLE
Release notes out of date?

### ISSUE THREAD

**Issue by mlissner** [kurtmckee/feedparser#249]
Looks like the docs don't have change logs for anything past the 4.x series, and we're now in the 6.0.1. Is it possible to get an update? We'd love to get the fix for py3.9 that landed recently, but it's scary not knowing what else might come along with that. 

I imagine this is hard to do retroactively, but maybe so little has changed that the log could just say that?

**Comment by kurtmckee** [comment]
Hi Mike!

I updated the changelog in the root of the repo, but not the .rst files. I'm currently looking for a better way to manage this, likely using a tool like scriv.

I'm very sorry for the inconvenience. A retroactive documentation update to make everything consistent might be a lot of work but I expect it will be worth it.

Please let me know if that answers your question!

**Comment by mlissner** [comment]
Shoot, I looked twice, but didn't see the changes file b/c I was looking for a file called "CHANGES" or "RELEASES". Mind if I do a PR to change "NEWS" to CHANGES.md"? I think that'd help at least until the automated method comes into play. You could also just forward people from the official docs to CHANGES.md and save yourself the trouble?

**Comment by kurtmckee** [comment]
Mine, that's a great idea, and it'll instantly help with automatic formatting within the GitHub interface!

If you rename the file, would you use the name CHANGELOG.rst? I'm interested in using restructured text so that the contents can be incorporated into the Sphinx documentation more easily.

Thanks for this great idea!

**Comment by mlissner** [comment]
Ok, I think PR #250 should make this good enough that once pulled folks won't be confused about where to find changes anymore. Somebody could take this further and either incorporate the github stuff into the real documentation or vice versa, but this ought to be good enough for a while. Anybody in the real docs will get redirected, and anybody on github will find what they're looking for.

The docs do a better job linking and explaining and formatting for the older versions, but most of that seems to be very old.

**Comment by kurtmckee** [comment]
Mike, thanks so much for contributing this. Great work!
