### ISSUE TITLE
Headers should be case insensitive according to spec

### ISSUE THREAD

**Issue by codeclem** [kurtmckee/feedparser#252]
From RFC 2616 - "Hypertext Transfer Protocol -- HTTP/1.1", Section 4.2, "Message Headers": https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.

Therefore `feedparser` should use a `CaseInsensitiveDict` from `requests.structures` to store headers.

For example if the server sends `cache-control` instead of `Cache-Control` then `feed.headers['Cache-Control']` won't work. But according to spec, it should.

**Comment by kurtmckee** [comment]
You are correct. However, feedparser will soon be retiring all of its internal HTTP client code. I don't anticipate making any changes to the HTTP client code moving forward.
