### ISSUE TITLE
Question: Writing parsed feeds back to RSS format...

### ISSUE THREAD

**Issue by seanmcfeely** [kurtmckee/feedparser#258]
Is there a recommended way to do this? I am filtering feeds for entry content I'm interested in. I'd then like to write the result to a new feed.

Thanks in advance!

**Comment by kurtmckee** [comment]
You could use a package like Django's [feedgenerator](https://pypi.org/project/feedgenerator/) to do this. However, I have limited experience with feedgenerator and I don't know if it will generate 1-to-1 identical input/output of feeds.

**Comment by person-al** [comment]
@seanmcfeely Did you get it working with feedgenerator? I'm looking to do the same thing.
