### ISSUE TITLE
Feature Request: Gemini Support 

### ISSUE THREAD

**Issue by ecliptik** [kurtmckee/feedparser#266]
This is a request to add support for the Gemini Protocol, which is a newer Internet protocol more lightweight than http and requires TLS.

https://gemini.circumlunar.space/docs/faq.html
https://gemini.circumlunar.space/docs/specification.gmi

Gemini sites have the ability to serve an XML feed similar to RSS through [gemfeed](https://tildegit.org/solderpunk/gemfeed), and the request is for feedparser to understand gemini:// and read a feed similar to an http:// site.

An example feed is here: gemini://rawtext.club/~ecliptik/_posts/feed.xml

**Comment by kurtmckee** [comment]
Hey Michael, thanks for the suggestion! Gemini looks interesting.

However, I'm not going to add additional communication protocols to feedparser. I see that there's at least one Python library for interacting with Gemini sites, so developers will be able to pull the feed across the wire and then parse the feed using feedparser.

**Comment by sjehuda** [comment]
Can we add support for Gemini Feed?

```py
from urllib.parse import urljoin

class Gemini:

    def gemini_feed(uri, content):
        feed = []
        for line in content.split('\n'):
            if line.startswith('=>'):
                line_split = line.split()
                entry = {
                    # 'content' : 'Content and summary would require download.',
                    'date' : line_split[2],
                    'link' : urljoin(uri, line_split[1]),
                    # 'summary' : 'First line after title should probably be summary.',
                    'title' : ' '.join(line_split[3:]) if len(line_split) > 3 else 'No title'
                    }
                feed.append(entry)
        return feed
```

It appears that `urljoin` does not work properly for Gemini URI scheme, albeit it does work with Gopher URI scheme.

**Comment by sjehuda** [comment]
Download from Gemini.

```py
import Agunua

class Gemini

    def download(uri: str) -> dict:
        data = Agunua.GeminiUri(uri, get_content=True, maxsize=5000000)
        if data.network_success and data.status_code == '20':
            result = {
                'charset': data.charset,
                'content': data.payload,
                'content_length': data.size,
                'content_type': data.mediatype,
                'error': None,
                'message': data.error,
                'original_url': uri,
                'status_code': data.status_code,
                'response_url': data.url}
            return result
```
