### ISSUE TITLE
No version Key, not allowed by Home assistant

### ISSUE THREAD

**Issue by yfands** [kurtmckee/feedparser#268]
Hello,

Got a warning:

Logger: homeassistant.loader
Source: loader.py:802
First occurred: 11:16:04 (3 occurrences)
Last logged: 11:16:08

No 'version' key in the manifest file for custom integration 'feedparser'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'feedparser'

**Comment by kurtmckee** [comment]
Hi @yfands! Thanks for reporting this. Unfortunately, this is not the correct "feedparser" project.

After reviewing Home Assistant's source code, it appears that this may be referring to a custom Home Assistant integration that reused the name "feedparser". For example, I found this custom Home Assistant integration named "feedparser":

https://github.com/custom-components/feedparser

Please review the custom integrations you have installed, then report this issue to the correct project.

Thanks, and have a great weekend!
