### ISSUE TITLE
Universal Encoding Detector link outdated?

### ISSUE THREAD

**Issue by kevbutler** [kurtmckee/feedparser#280]
On the [Character Encoding Detection](https://feedparser.readthedocs.io/en/latest/character-encoding.html#advanced-encoding) page of the docs, the link for the Universal Encoding Detector (http://chardet.feedparser.org/) does not work. I searched around and I think the new link should be https://chardet.github.io/ (or, alternatively, https://github.com/chardet/chardet). Is this the right project?

**Comment by kurtmckee** [comment]
Yep, that's correct. I'll work to get that link fixed. Thanks for reporting this!

**Comment by kurtmckee** [comment]
This is fixed in feedparser 6.0.8. The documentation should regenerate automatically to reflect the changes. Thanks for reporting this!
