### ISSUE TITLE
How to detect invalid RSS feeds?

### ISSUE THREAD

**Issue by jack1142** [kurtmckee/feedparser#283]
This is not really a bug but maybe a potential feature request. I'm currently trying to figure out the best way to detect invalid RSS feeds when accepting arbitrary feeds.

One potential way I'm seeing would be to check whether the root tag is called "rss" (or potentially some other names since I see you also have "feed" in your test cases for example) but that's not currently exposed by feedparser (that's the feature request part though as you can see I am not yet sure it would be useful).

Another way could be checking for the "title" tag since [it appears to be required](https://cyber.harvard.edu/rss/rss.html#requiredChannelElements) though perhaps there are some feeds out there that don't have it.

Do you have any experience with what might be the best way to detect invalid RSS feeds?

Here's one example of a *temporarily* invalid feed I ran into and made me wonder whether there's some good way to detect invalid RSS feeds aside from the existing `bozo` bool.
## FeedParser obj
```py
{
    "bozo": False,
    "entries": [],
    "feed": {
        "script": {"src": "/js/sf.js"},
        "meta": {
            "name": "description",
            "content": "Free, secure and fast downloads from the largest Open Source applications and software directory - SourceForge.net",
        },
        "summary": "<noscript>\nWe're sorry -- the Sourceforge site is currently in Disaster Recovery mode.  Please check back later.\n</noscript>",
    },
    "headers": {},
    "content-type": "",
    "encoding": "utf-8",
    "version": "",
    "namespaces": {},
}
```
## HTML
```html
<html><head>
<title>SourceForge</title>
<!-- <script src="/js/jquery.com/jquery-1.11.0.min.js"></script> -->
<script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="https://sourceforge.net/js/mirrors.js"></script>
<script src="/js/sf.js"></script>
<script>
var DR_loc = DR_parse_hash_url();
if (DR_loc) {
    DR_sf_main(DR_loc);
} else {
    window.location.href = \'https://sourceforge.net/home.html\';
}
</script>
<meta name="description" content="Free, secure and fast downloads from the largest Open Source applications and software directory - SourceForge.net"/>
</head><body>
<noscript>
We\'re sorry -- the Sourceforge site is currently in Disaster Recovery mode.  Please check back later.
</noscript>
</body></html>
```

**Comment by kurtmckee** [comment]
@jack1142, I think the `bozo` bool is usually going to indicate that the XML is not well-formed or that there's an issue with the declared character encoding. I don't think there's a lot of validation of the actual content.

There are three possibilities I can think of for validating the feed:

1. Check the HTTP status return. If you're seeing anything other than HTTP 200 there may be an issue.
2. Check the feed type. If it's blank or doesn't exist, feedparser hasn't seen the opening XML tags that indicate what type of feed it is (Atom 1.0, RSS 2.0, etc).
3. Sniff the content before passing it to feedparser. This may give you a better idea what you're dealing with.

I hope that helps!
