### ISSUE TITLE
feedparser ModuleNotFoundError

### ISSUE THREAD

**Issue by Mahdi-Ba** [kurtmckee/feedparser#295]
**Hello dears**
this is my requirement (althought without django and another os and python version try again) try again when import it  Error happend
ModuleNotFoundError: No module named 'feedparser'
`import feedparser`
- Python 3.7.10
- asgiref==3.4.1
- backports.zoneinfo==0.2.1
- certifi==2021.10.8
- charset-normalizer==2.0.9
- Django==4.0
- djangorestframework==3.12.4
- feedparser==6.0.8
- idna==3.3
- requests==2.26.0
- sgmllib3k==1.0.0
- six==1.16.0
- sqlparse==0.4.2
- transforms==0.1
- urllib3==1.26.7

Thanks

**Comment by kurtmckee** [comment]
Possibly so! It doesn't seem to be related to feedparser but I'm glad you got it resolved!
