### ISSUE TITLE
[Feature Request] Parsing HTML5 Pages

### ISSUE THREAD

**Issue by sjehuda** [kurtmckee/feedparser#309]
It appears that the only Feed reader to handle `<article/>` tags is [Liferea](https://github.com/lwindolf) of Mr. Larse Windolf @lwindolf.

Intoduction:
[Subscribing To Html5 Websites That Have No Feed](https://lzone.de/liferea/blog/Subscribing-to-HTML5-websites-that-have-no-feed)

First commit:
[Add support for subscribing to HTML5 websites without RSS/Atom feeds by extracting article titles, links and descriptions](https://github.com/lwindolf/liferea/pull/815)

Last commit to daye:
[Improve HTML5 extraction: extract <main> if it exists and no article was found](https://github.com/lwindolf/liferea/commit/a4ac661a98619e075e34dbcaea120c79977fae72)

Test page:
https://miranda-ng.org/
https://www.brandenburg.de/
http://intertwingly.net/blog/

Frankly, this is one of the best features of Liferea to date, namely because novice users don't need to handle scrapping for pages with `<article/>` tag.

**Comment by kurtmckee** [comment]
You haven't actually reported a bug or requested a feature. I can guess what the point is, but please modify the text of your issue to include a feature request or a bug report. Thanks!

**Comment by kurtmckee** [comment]
Thanks! So the request is: support extracting feed items directly from HTML data?

**Comment by sjehuda** [comment]
On Thu, 19 May 2022 06:35:32 -0700
Kurt McKee ***@***.***> wrote:

> Thanks! So the request is: support extracting feed items directly
> from HTML data?
> 

Yes, but only on certain occasions, just like Liferea.
Of course, this leaves use with a limited options because we are
guessing an </article> entry.

Apparently, some websites that don't provide feeds, are useful when
treated as feeds, hence I think a very-specific guessing mechanism is
worth to have.

**Comment by sjehuda** [comment]
I didn't know there's a specs documentation for `</article>`.
h-feed spec is definitely worth adding.
I just don't think that something so specific, let alone can be done by a relatively simple external script, is a sensible addition to feedparser.
