### ISSUE TITLE
Feature Request: Fingerprint for RSS 2.0

### ISSUE THREAD

**Issue by danielniccoli** [kurtmckee/feedparser#322]
Unlike ATOM 1.0 with the `id` field, RSS 2.0 has no meaningful way of reliably identifying an item (feed entry). An RSS item has the `guid` field, but it is optional.

> […]  All elements of an item are optional, however **at least one of title or description must be present**. […]
  [Specs](https://www.rssboard.org/rss-specification#hrelementsOfLtitemgt)

I would like to suggest that for RSS items the parser generates a fingerprint, if no guid is available.

Example code:

```python
from hashlib import sha1

if not guid:
    m = sha1()
    m.update(str.encode(title + description))
    fingerprint = m.hexhdigest()
```

**Comment by auouymous** [comment]
The title and description are often modified in feeds, making that fingerprint unstable. Enclosure URLs can change if the feed switches to a new CDN, but some feeds actually share the same enclosure across multiple items. The link URL is also shared across items for multi-part episodes that share a single page.

Any strategy feedparser chooses would be unstable.

**Comment by danielniccoli** [comment]
If a feed is so badly formatted that is provides no guid, then a fingerprint for title and description is the only thing that you can use to somewhat reliably identify an entry in a feed. If one of both changes, then yeah, you can never know whether it is a modified or new item. So finerprint is still the best option here.

> Any strategy feedparser chooses would be unstable.

Yes, but that's due to the horrible RSS design. My suggestion is still the less horrible option of the two. And it's optional to use, but when you know what it does, once can use it to its advantage.

**Comment by kurtmckee** [comment]
This is outside the scope of feedparser. Downstream clients can independently implement a strategy for uniquely fingerprinting incoming feed items.

The example code you shared is a great example of what a downstream client could do when upserting a feed item into a database. :+1:
