### ISSUE TITLE
cgi deprecation warning

### ISSUE THREAD

**Issue by mailint-daniellee** [kurtmckee/feedparser#330]
feedparser\encodings.py:29

DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13

**Comment by kurtmckee** [comment]
Thanks for notifying me about this! I'll try to get that updated. Thank goodness there's a little time...

**Comment by derekwisong** [comment]
Noticed that this commit: https://github.com/kurtmckee/feedparser/commit/ed8c762286aa1d8a248a6900190bd02c01ac2f8d was addressed that problem 10 months ago, and on the same day as the 6.0.10 release to PyPI, but the version in PyPI doesn't have the change... https://pypi.org/project/feedparser/6.0.10/

**Comment by owenlamont** [comment]
Will there be another PyPi release soon? I'm keen to get this cgi fix.

**Comment by Safihre** [comment]
Please release another version.
Python 3.13 Alpha 1 is out so it's time 😉

**Comment by lyz-code** [comment]
@kurtmckee can we have a release to fix this issue please?

**Comment by Safihre** [comment]
Seems he abandoned it again.. Maybe somebody should fork it that is able to provided regular updates.

**Comment by kurtmckee** [comment]
feedparser 6.0.11 should resolve this issue.

It makes no other code changes than to resolve the cgi deperaction warning.

**Comment by Safihre** [comment]
Thank you!

**Comment by kurtmckee** [comment]
You're welcome! :grinning:
