### ISSUE TITLE
the example from the documentation fails with an error

### ISSUE THREAD

**Issue by KopylovVadik** [kurtmckee/feedparser#341]
the example from the documentation fails with an error

**Comment by KopylovVadik** [comment]
`
import feedparser
d = feedparser.parse('http://feedparser.org/docs/examples/rss20.xml')
d.feed.title
`

**Comment by kurtmckee** [comment]
Thanks for reporting this! I'll see if I can re-host those examples on ReadtheDocs.

**Comment by kurtmckee** [comment]
This should be fixed now.
