### ISSUE TITLE
`py.typed` is missing from current release on pypi

### ISSUE THREAD

**Issue by sbrudenell** [kurtmckee/feedparser#373]
Given
```python3
import feedparser
feedparser.parse("test")
```
A straightforward type-check fails:
```shell
$ python3 -m venv v
$ source v/bin/activate
(v) $ pip install feedparser mypy
...
(v) $ mypy t.py
t.py:1: error: Skipping analyzing "feedparser": module is installed, but missing library stubs or py.typed marker  [import]
t.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

I see `py.typed` is present in the source code. If I manually download the current `*.whl` from pypi, I do not see `py.typed`.

If I clone the repo locally and do `pip install .`, then I see `py.typed` in my venv and `mypy` type-checks the test file. (This also required `pip install chardet types-requests` for further typing dependencies)

If I do `pip wheel .` in a local clone, I do see `py.typed` in the `*.whl`.

Perhaps something is going wrong at a packaging step? I couldn't find any packaging/publishing workflow in the github actions config, so I can't diagnose further.

**Comment by kurtmckee** [comment]
Releases are created from the `master` branch (which will renamed to `releases` in the future).

When feedparser 7 is released it will include the `py.typed` file.

**Comment by eggplants** [comment]
Any update on next release? Latest master branch (32adbe1) is [236 commits behind](https://github.com/kurtmckee/feedparser/compare/32adbe1...696d5b9) develop branch (696d5b9).
