### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by psmoros** [kurtmckee/feedparser#374]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@benasin) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by kurtmckee** [comment]
That's a good idea! Let me read some docs about GitHub's interface for this. In the meantime, my public email address is posted on my profile (@kurtmckee) and you can send information to me via that route. Thanks!

**Comment by Benasin** [comment]
Hi guys, are there any updates on the Security Issue?

**Comment by kurtmckee** [comment]
Yes, I told you to send an email to my email address.

**Comment by jasnow** [comment]
Having an official point of contact is super important when someone
finds a vulnerability and wants to responsibly report it.
The "Security" button on GitHub repos shows what a project's 
Security Policy is as defined by the Security.md file.

**Comment by kurtmckee** [comment]
You are correct, and I haven't implemented it yet. I have responded how this particular issue can be reported in the meantime.
