### ISSUE TITLE
Docs: Wrong link to Python Unicode tutorial

### ISSUE THREAD

**Issue by aaaaalbert** [kurtmckee/feedparser#381]
Cheers, [your intro document](https://github.com/kurtmckee/feedparser/commit/fc3e6397cebd0e4c96a51417894d6a8ef41ec998#diff-24cb7e9441a980494ad3ffabb5741f3c84edf186e7f52a0f1df68c8a74b0a981R78) currently contains an outdated link to a Python 2.7 Unicode tutorial. Python 2.7 is also outdated.

I *think* the new version of that old tutorial link should be [this](https://docs.python.org/2.7/tutorial/introduction.html#unicode-strings), **but** `feedparser` only supports Python 3.8+ anyway. 

Two options for fixing this would be: remove the tutorial link altogether, or link to an up-to-date piece of Python 3 documentation.

If you fancy the contribution, I'm happy to send a PR for either solution. Just let me know.

**Comment by kurtmckee** [comment]
Yikes. Great catch! I can simply remove that. Thanks for pointing this out!

**Comment by aaaaalbert** [comment]
Awesome, thanks for the quick reply!

**Comment by aaaaalbert** [comment]
:clap:
