### ISSUE TITLE
Relative link resolution doesn't work for some <img>

### ISSUE THREAD

**Issue by dzeban** [kurtmckee/feedparser#43]
According to [documentation](http://pythonhosted.org/feedparser/resolving-relative-links.html) `<img src="">` is treated as URI and its link is resolved.

But I found the case where it doesn't work, Atom feed at http://jvns.ca/atom.xml

``` python
> import feedparser
> feedparser.__version__
'5.2.1'
> feedparser.RESOLVE_RELATIVE_URIS
1
> feed = feedparser.parse('http://jvns.ca/atom.xml')
> # This entry has img with relative URI
> e = feed['entries'][4]
> # Get HTML content
> content = e['content'][0]['value']
> # Find and show <img>
> i = content.find('img src')
> print(content[i-1:(i+50)])
<img src="/images/ml-feelings.jpg" width="300px" />
```

As you can see image source remained relative

**Comment by tabascoterrier** [comment]
I'm seeing this with certain atom feeds too.  @dzeban, did you ever find a resolution for this?

**Comment by tabascoterrier** [comment]
I found my answer on the https://pypi.org/project/feedparser/ page.  

It turns out that relative link resolution relies on sgmllib, which is no longer part of Python 3.  The zip download on the pypi page contains a Python 3 compatible sgmllib library, and adding that to my project directory resolves for me.

**Comment by rlskoeser** [comment]
Glad this issue was here, helped me get on the right track.

I was able to resolve the problem by installing [sgmllibpy3k](https://pypi.org/project/sgmllib3k/).  It's an unmaintained port of the python2 module, but works for now.

**Comment by kurtmckee** [comment]
feedparser 6.0.0 has been released and requires sgmllib3k as a mandatory dependency. This shouldn't be an issue anymore.
