### ISSUE TITLE
Undeclared `pluggy` dependency for test suite

### ISSUE THREAD

**Issue by adigitoleo** [kurtmckee/feedparser#437]
Currently updating the Void linux package. Noticed that `pluggy` is required to run the tests but not declared in `pyproject.toml`. Just a heads up.

**Comment by kurtmckee** [comment]
feedparser's test suite doesn't import `pluggy`. It might be a transient dependency via pytest, but it's not a direct dependency of feedparser.

**Comment by adigitoleo** [comment]
Indeed this was actually a case of our tox package not declaring pluggy as a dependency. My mistake.

**Comment by kurtmckee** [comment]
No worries! I appreciate you raising this issue. Have a great day!
