### ISSUE TITLE
Bottleneck, significant cpu time spent on datetimes

### ISSUE THREAD

**Issue by sciunto** [kurtmckee/feedparser#44]
Hi,

I'm using rss2email by @wking and I ran some measurements to find the bottleneck because I found that rss2email a bit slow.

I used line_profiler to measure the cpu time.

From my investigations, I noticed that 
* most of the time is used by feedparser (not a big surprise, but good to check, excluding IOs)
* more precisely, http.py function `_build_urllib2_request`
* in this function, about 50% is used by `urllib.request.Request(url)` and 50% by `_parse_date(modified)`

Clearly, this function takes a lot of time and can probably be optimized. I leave this note as an open question for suggestions from experts.

From my feeds, rfc822 seems to be mostly used.

Thank you.

**Comment by sciunto** [comment]
After further investigation. email.utils functions gives similar perfomances compared to #45.
We cannot probably do better than #45.

**Comment by kurtmckee** [comment]
@sciunto thanks for the patch! Also, note that most obscure date/time formats are converted to something compatible with RFC822 and then RFC822 is called to do the actual parsing. Thus, the RFC822 parser is heavily used.

I once did a performance test and found the procedural code was significantly faster than even a pre-compiled regex-based parser, so this may be up toward the limit of what's possible currently.

I'm interested in improving feedparser's performance but want to close this bug now that #45 is merged. (And note that I intend to get rid of feedparser's URL-fetching code and just use the requests library in the future, so the _build_urllib2_request garbage will go away in the future.)

Thanks again for the patch, I really appreciate it!
