### ISSUE TITLE
Parse item image tag from RSS feed

### ISSUE THREAD

**Issue by pieterclaerhout** [kurtmckee/feedparser#48]
In the following feed, each item has an "image" attribute. Any chance you can use feedparser to access this element?

https://iso.500px.com/feed/

Kind regards,

pieter

**Comment by pieterclaerhout** [comment]
Turns out that the feed is not valid (missing the namespace to make it recognize the image tag).

It would be helpful if we could get access to the raw attributes of an RSS item so that we can handle this ourselves if needed.

**Comment by kurtmckee** [comment]
Yes, this is referenced in #24. feedparser will never be an XML DOM parser (that is, catching all elements and attributes blindly) but it's critically important that it expose an API for parsing elements and attributes that people are interested in. I'll update #24 once something is in place to accommodate these kinds of requests. Thanks for opening this ticket!
