### ISSUE TITLE
Timezone handling

### ISSUE THREAD

**Issue by dmwyatt** [kurtmckee/feedparser#51]
I might be blind, but I don't see anything in the documentation specifying any sort of guarantee on timezone parsing.  From the [examples](https://pythonhosted.org/feedparser/date-parsing.html#recognized-date-formats) it *looks* like it always returns GMT time...

The `struct_time` object it spits out for the various datetime fields doesn't have the `tm_zone` or `tm_gmtoff` [attributes](https://docs.python.org/3/library/time.html#time.struct_time) on my system.

Can I assume that the time it provides is always in GMT?  What if the feed doesn't provide a timezone...will it just be assumed as GMT?

**Comment by kurtmckee** [comment]
Yes, feedparser's returns UTC datetime tuples, but I'll make sure this is documented.

If no datetime is provided feedparser will assume UTC *but* if you encounter a situation where this is not the case don't hesitate to open a ticket! =)

I'll close this only after confirming the UTC normalization is documented.
