### ISSUE TITLE
Allow turning off sanitization

### ISSUE THREAD

**Issue by frioux** [kurtmckee/feedparser#55]
I understand that sanitization is for my safety, but there are times when it is silly to do and changes the feed enough to be "too much."  Would you accept a pull request to disable the sanitization at the user's request?  Maybe based on a flag passed to parse?

**Comment by daniellam** [comment]
I have the same problem, but i found that it can be disabled by setting a flag like so
``
        feedparser.SANITIZE_HTML = 0
        d = feedparser.parse(url)
``

**Comment by twm** [comment]
Do you have a use case where `feedparser.SANITIZE_HTML = False` is insufficient? Otherwise, I think that we can close this issue.

**Comment by frioux** [comment]
that's global, instead of object scoped, but works.  Since opening this ticket I've stopped using feedparser anyway, so whatevs.
