### ISSUE TITLE
cjkpython gone

### ISSUE THREAD

**Issue by dmwyatt** [kurtmckee/feedparser#57]
The docs [here](https://github.com/kurtmckee/feedparser/blob/develop/docs/character-encoding.rst) recommend installing a couple of packages from http://cjkpython.i18n.org/

i18n.org has been gone for long enough that Google's last cached copy of it was a godaddy hosting page.

So, I guess we need to figure out what the current recommended guidance here is and then update the docs.

**Comment by kurtmckee** [comment]
Dustin, great catch, I'll review this soon. Thanks for reporting this!
