### ISSUE TITLE
Service document (RFC 5023) not parsed properly

### ISSUE THREAD

**Issue by PlkMarudny** [kurtmckee/feedparser#64]
Trying to parse s simple document that consist only of several collections, produces 'collection' as a single entry dictionary with only one url - the last one in the document.

**Comment by mmcdole** [comment]
@PlkMarudny any way you can attach an example?

**Comment by PlkMarudny** [comment]
Here is the document that was the source of the problem described above:

`<service xmlns="http://www.w3.org/2007/app" xmlns:a10="http://www.w3.org/2005/Atom" xmlns:vizrt="http://www.vizrt.com/xmlns/types"><app:workspace xmlns:app="http://www.w3.org/2007/app"><a10:title type="text">Pilot App Server</a10:title><app:collection href="http://10.99.10.34:8177/templates" vizrt:type="templates"><a10:title type="text">Template list</a10:title><app:categories><a10:category term="templates" label="templates" scheme="http://www.vizrt.com/types"/></app:categories></app:collection><app:collection href="http://10.99.10.34:8177/dataelements" vizrt:type="elements"><a10:title type="text">Dataelement list</a10:title><app:categories><a10:category term="elements" label="elements" scheme="http://www.vizrt.com/types"/></app:categories></app:collection><app:collection href="http://10.99.10.34:8177/concepts" vizrt:type="concepts"><a10:title type="text">Concept list</a10:title></app:collection><app:collection href="http://10.99.10.34:8177/external_ids" vizrt:type="external_ids"><a10:title type="text">External id list</a10:title></app:collection><app:collection href="http://10.99.10.34:8177/vos/images"><a10:title type="text">Images</a10:title><app:accept>image/png</app:accept><app:accept>image/jpg</app:accept><app:categories><a10:category term="asset" label="asset" scheme="http://www.vizrt.com/types"/><a10:category term="search" label="search" scheme="http://www.vizrt.com/types"/></app:categories><a10:link href="http://10.99.10.34:8177/vos/open_search/images" rel="search" type="application/opensearchdescription+xml"/></app:collection><app:collection href="http://10.99.10.34:8177/vos/persons"><a10:title type="text">Persons</a10:title><app:categories><a10:category term="person" label="person" scheme="http://www.vizrt.com/types"/><a10:category term="search" label="search" scheme="http://www.vizrt.com/types"/></app:categories><a10:link href="http://10.99.10.34:8177/vos/open_search/persons" rel="search" type="application/opensearchdescription+xml"/></app:collection><app:collection href="http://10.99.10.34:8177/tags" vizrt:type="tags"><a10:title type="text">Tag list</a10:title></app:collection></app:workspace><a10:link href="http://10.99.10.34:8177/vcp/parameters" rel="vcp_settings" type="application/vnd.vizrt.payload+xml"/><a10:link href="http://viz-car2-prv1:54000/" rel="preview_server"/><a10:link href="http://dxb-vizora-01:1981/" rel="script_runner"/></service>`

**Comment by kurtmckee** [comment]
@PlkMarudny this is not a feed and is not a target format for feedparser. It's referencing the Atom namespace elements to use the meaning of Atom's existing ``title`` and ``category`` elements, but is not a feed.
