### ISSUE TITLE
Introduction in feedparser docs needs new URL

### ISSUE THREAD

**Issue by MattDMo** [kurtmckee/feedparser#71]
From the very first code bit on the [Introduction page](https://pythonhosted.org/feedparser/introduction.html):

``` py
>>> import feedparser
>>> d = feedparser.parse('http://feedparser.org/docs/examples/atom10.xml')
```

All seems to work OK, except:

``` py
>>> d["feed"]["title"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/feedparser.py", line 357, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'title'
```

The source of atom10.xml is

``` html
<!DOCTYPE html>
<body style="padding:0; margin:0;">
<html>
<body>
    <iframe src="http://mcc.godaddy.com/park/p3WlpJAhMJMlMF5vMKD=" style="visibility: visible;height: 100%; position:absolute" allowtransparency="true" marginheight="0" marginwidth="0" frameborder="0" width="100%">
    </iframe>
</body>
</html>
```

(I formatted it, as it was all on one line). From what I can gather, the domain is parked but has no content. So, if you own the domain, could you an acceptable RSS feed file at the indicated URL? If not, could you find another sample RSS feed to use? You could probably just post a file on Github or something.

Thanks!

**Comment by MattDMo** [comment]
OK, I didn't read far enough (this is my first time going through the tutorial). Apparently [this page](https://pythonhosted.org/feedparser/common-rss-elements.html) has a non-functional feedparser.org URL as well. I don't have time tonight to go through all the `.rst` files and search for bad URLs, but it's a trivial exercise if you know how to `grep` :grinning:

**Comment by noMICROSOFTbuhtz** [comment]
Related to #166

**Comment by kurtmckee** [comment]
Thanks for bringing this to my attention! I thought that I did a grep for this years ago but I guess I didn't. =(

I'll get this fixed soon!
