### ISSUE TITLE
bozo detection

### ISSUE THREAD

**Issue by foxmask** [kurtmckee/feedparser#81]
With the bozo detection, my Feeds seem to be not ok

``` python
 >>> data = feedparser.parse('https://foxmask.trigger-happy.eu/feeds/all.rss.xml')
 >>> data.bozo
1
 >>> data.bozo_exception
CharacterEncodingOverride('document declared as us-ascii, but parsed as utf-8',)
```

but when I use chardet, the encoding is well parsed and encoding well detect

``` python
 >>> data = urlopen('https://foxmask.trigger-happy.eu/feeds/all.rss.xml').read()
 >>> chardet.detect(data)
{'confidence': 0.99, 'encoding': 'utf-8'}
```

What can I do to make the bozo detection works well ?

**Comment by planb3** [comment]
I encountered the same problem, I ask you to solve?

**Comment by kevinmarks** [comment]
Add a line like this at the top:

<?xml version="1.0" encoding="utf-8"?>

**Comment by foxmask** [comment]
And suppose it's à Feed on which you do not have the hand to add that Line ?

**Comment by foxmask** [comment]
In fact, the feeds https://foxmask.trigger-happy.eu/feeds/all.rss.xml already starts by this prolog

```xml
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>Le Free de la Passion</title>
```

**Comment by foxmask** [comment]
Hi, any news ?

**Comment by foxmask** [comment]
I made a check with https://validator.w3.org/feed/ and it looks like that the server did not return the expected charset. 
Even if the validator tell my Feeds is valid, that was not the case for feedparser. 
So, as suggested by the Validator, I changed the default charset and set it to the same as the RSS Feed and now  : 

```python
(django-trigger-happy) >>> import feedparser
(django-trigger-happy) >>> d = feedparser.parse('https://foxmask.trigger-happy.eu/feeds/all.rss.xml')
(django-trigger-happy) >>> d.bozo
0
```
