### ISSUE TITLE
How to check whether the passed url is a valid rss feed

### ISSUE THREAD

**Issue by rohitkhatri** [kurtmckee/feedparser#86]
I'm trying to validate the url, like If I pas `feedparser.parse('http://rohitkhatri.com')`, It should give me false.

Is there any property which I can access to get this information?

**Comment by kevinmarks** [comment]
The number of entries being 0?

**Comment by rohitkhatri** [comment]
@kevinmarks Yes, no. of entries is zero, will that be fine to validate an rss feed?

**Comment by rohitkhatri** [comment]
I solved it by checking number of entries, thanks to @kevinmarks :-)

**Comment by tyronexj** [comment]
not sure if correct
```
d = feedparser.parse('invalid_url')
if d.status != 200:
   invalid_url
```
